GET http://127.0.0.1:3000/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJmMWMyNzQzYTJhZmY3YmZmZDBmODRhODY0ZTljMjc4ZjMxYmM2NTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmlmdGhwYXJrLXRlc3QiLCJhdWQiOiJmaWZ0aHBhcmstdGVzdCIsImF1dGhfdGltZSI6MTY1ODYzNjc1MiwidXNlcl9pZCI6IlltT2libEJoNnRZQ21GREhmZzROYUZHZnRSSjIiLCJzdWIiOiJZbU9pYmxCaDZ0WUNtRkRIZmc0TmFGR2Z0UkoyIiwiaWF0IjoxNjU4NjM2NzUyLCJleHAiOjE2NTg2NDAzNTIsImVtYWlsIjoibmFrYXlvc2hpQG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm5ha2F5b3NoaUBtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.TbcqZ8RTZtHDZUzSHTLCtJp06ald1gWfKWFbUqFtkmk-4lC2ClM2U9AZGlB4BToipDaH7j-j1qyFlqmP78feLvZewxbKwDPIl_5xUoXqWLQNYzv81Hvo1k9lIKY99TDQJabJpgWzjgllv5w4nnJgvXsi9WSg_cpoyAdH-7O1aaA5AFqLe1h1qKwFMAFf6HEHALBNz1fbT-cyQbFLPChbY2Wp2sH2SdCTbtt1fGd02ST_P054uwqt4q7MrqVn4ikV424-1NfKO-u80FrvOqdd5vMoS7hdMVtDrcyfPX9y4O5uBJPNo9ZmRK-8fwX-kv2ycKZm2Kl8ofjUT57NMSRjew

{
}